spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200ms
  application:
    name: simulator-service-testing
  datasource:
    url: jdbc:mysql://localhost:3306/simulator_service
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG
    com.project.hems.simulator_service_testing: info

server:
  port: 9010

simulation-redis:
  config:
    redis-key: "simulator:userId:"
