spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200ms

  application:
    name: simulator-service-testing

  datasource:
    url: jdbc:mysql://localhost:3306/simulator_service
    username: 
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      acks: 1
      bootstrap-servers:
      - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  

server:
  port: 9010

simulation-redis:
  config:
    redis-key: "simulator:siteId:"

property:
  config:
    kafka: 
      raw-energy-group-id: raw-energy-readers
      raw-energy-topic: RAW_ENERGY_READINGS
      raw-energy-partition-count: 3

      replica-count: 1
