spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200ms
  application:
    name: simulator-service-testing
  datasource:
    url: jdbc:mysql://localhost:3306/simulator_service
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      bootstrap-servers:
      - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  
    
    consumer:
      bootstrap-servers:
      - localhost:9092
      group-id: dispatch-command-readers
      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      # Ignore the type info sent by the producer
      spring.json.use.type.headers: false
      spring/.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      # Ensure the package is trusted
      spring.json.trusted.packages: "*"
      spring.json.type.mapping: "com.project.hems.envoy_manager_service.model.EnergyDispatchCommand:com.project.hems.simulator_service_testing.model.EnergyDispatchCommand"
      # Specify the local class to always use for this consumer
      spring.json.value.default.type: com.project.hems.simulator_service_testing.model.EnergyDispatchCommand

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG
    com.project.hems.simulator_service_testing: debug

server:
  port: 9010

simulation-redis:
  config:
    redis-key: "simulator:siteId:"

property:
  config:
    kafka: 
      raw-energy-topic: RAW_ENERGY_READINGS
      energy-dispatch-topic: ENERGY_DISPATCH_COMMANDS
      partition-count: 3
      replica-count: 1
