spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200ms
  application:
    name: simulator-service-testing
  datasource:
    url: jdbc:mysql://localhost:3306/simulator_service
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      bootstrap-servers:
      - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG
    com.project.hems.simulator_service_testing: debug

server:
  port: 9010

simulation-redis:
  config:
    redis-key: "simulator:userId:"

property:
  config:
    kafka: 
      topic: BATTERY_STATS
      bootstrap_servers: localhost:9092
